version: "3.3"

services:
    reverse:
        image: nginx
        hostname: reverse
        container_name: reverse
        ports:
          - 80:80
          - 443:443
        volumes:
          - ./reverse-proxy/confs/config/conf.d:/etc/nginx/conf.d
          - ./devcerts/private:/etc/ssl/private
          - ./reverse-proxy/logs:/var/log/nginx
        networks:
          - docker_network

    nginx:
        image: nginx
        container_name: nginx
        restart: always
        working_dir: /var/www/magento2
        volumes:
            - ./magento:/var/www/magento2
            - ./nginx_logs:/var/log/nginx
            - ./confs/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - docker_network 

    #PHP-FPM
    php:
        image: m2php73
        container_name: php
        volumes: 
            - ./magento:/var/www/magento2
        ports:
            - 9000:9000
        user: www-data
        networks:
            - docker_network

    #Maria DB
    mysql:
        image: mariadb:latest
        container_name: mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: allthingslarge
        volumes: 
            - db-data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - docker_network

    #PHPmyAdmin
    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - PMA_USER=root
            - PMA_PASSWORD=root
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PHP_MAX_INPUT_VARS = 18000
        ports:
            - 8011:80
        networks:
            - docker_network

    #Mailhog
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        restart: always
        ports:
            - 8025:8025
            - 1025:1025
        networks:
            - docker_network

    #ElasticSearch
    es01:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
        container_name: es01
        restart: always
        environment:
          - node.name=es01
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
          - data01:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300
        networks:
            - docker_network

volumes:
    data01:
        driver: local
    db-data:
        external: false
       
networks:
    docker_network:
        driver: bridge

